### ISSUE TITLE
New-PUTicket ser ikke ut til å fungere

### ISSUE THREAD

**Issue by PowershellKnut** [NorskNoobing/NN.Pureservice#1]
Når jeg forsøker å opprette en ny sak med New-PUTicket, virker det som at den bare lister ut en haug/alle sakene i Pureservice uten å opprette noe. Får ingen feilmeldinger heller.

**Comment by NorskNoobing** [comment]
Er en liten stund siden jeg har brukt Pureservice, men skal skaffe meg en demo og teste litt selv. Ser ikke ut som APIen har endret noe særlig på seg ut ifra det jeg ser i PS API-docs:
https://api-docs.pureservice.com/#aba3e60a-1f75-4ac1-98fe-52b7f79ff624

Har dere flere zones i deres Pureservice installasjon, eller er det bare et enkelt oppsett med 1 zone?

**Comment by NorskNoobing** [comment]
Jeg fant et lite script som du muligens kunne ha prøvd ut. Her må man endre på `Dynamic values` i param blokken til å matche deres Pureservice installasjon. Alle disse verdiene burde være mulig å finne ved å både se på eksisterende tickets, eller ved bruk av de andre funksjonene.
```powershell
param (
    #Non-default values
    [string]$Subject = "test av API æøå",
    [string]$Description = "test123 123test! æøå",
    [string]$AgentUsername = "AGENT_USERNAME",
    [string]$AssignedUsername = "ENDUSER_USERNAME",

    #Dynamic values
    [string]$PriorityName = "Normal",
    [string]$StatusName = "Ny",
    [string]$TeamName = "IT-servicedesk_test",
    [string]$TicketTypeName = "Problem",
    [string]$DepartmentName = "IT-seksjonen(test)",
    #Depends on whether the inquiry is on chat, phone, direct, or mail
    [string]$SourceName = "Direkte",

    #Static values
    [string]$VisibilityName = "Visible"
)

#Install required modules
$RequiredModulesNameArray = @('NN.Pureservice')
$RequiredModulesNameArray.ForEach({
    if (Get-InstalledModule $_ -ErrorAction SilentlyContinue) {
        Import-Module $_ -Force
    } else {
        Install-Module $_ -Force -Repository PSGallery
    }
})

$PriorityId = (Get-PuPriorities).where({$_.name -like $PriorityName})[0].id
$SourceId = (Get-PuSources -Type "Ticket").where({$_.name -like $SourceName})[0].id
$StatusId = (Get-PuStatuses).where({$_.name -like $StatusName})[0].id
$TeamId = (Get-PuTeams).where({$_.name -like $TeamName})[0].id
$AgentId = (Get-PuUsers -filter @"
!Disabled AND (role == `"Agent`" || role == `"Administrator`") AND (credentials.username==`"$AgentUsername`")
"@)[0].id
$UserId = (Get-PuUsers -filter @"
!Disabled AND (credentials.username==`"$AssignedUsername`")
"@)[0].id
$VisibilityId = (Get-PuVisibilityList).where({$_.Name -like $VisibilityName})[0].id
$TicketTypeId = (Get-PuTypes -TypeCategory "Ticket").where({$_.Name -like $TicketTypeName})[0].id
$DepartmentId = (Get-PuDepartments).where({$_.name -like $DepartmentName})[0].id

$Splat = @{
    "subject" = $Subject
    "description" = $Description
    "visibility" = $VisibilityId
    "user" = $UserId
    "ticketType" = $TicketTypeId
    "priority" = $PriorityId
    "status" = $StatusId
    "source" = $SourceId
    "assignedDepartment" = $DepartmentId
    "assignedTeam" = $TeamId
    "assignedAgent" = $AgentId
}
New-PuTicket @splat
```

Det eneste som er litt dumt med dette scriptet er at det henter ut mesteparten av IDs ved hjelp av displaynames som kan endre på seg. Derfor ville jeg heller ha hentet ut alle IDene du trenger til å opprette en sak på forhånd, så lime de inn som statiske verdier i scriptet. Dette kan gjøres ved å kjøre f.eks. `Get-PuVisibilityList` for å finne visibility IDen du skal bruke.

Naturligvis vil du mest sannsynelig ikke ha alle verdier statisk, som f.eks. `subject`,`description`,`user` og `agent`, men du vil trolig kunne sette resten av verdiene til statiske IDer.

Etter verdiene er lagt inn, så vil `New-PuTicket` scriptet se noe slik ut:
```powershell
$Splat = @{
    "subject" = "Tittel"
    "description" = "Beskrivelse"
    "visibility" = 1
    "user" = 12
    "ticketType" = 1
    "priority" = 2
    "status" = 3
    "source" = 1
    "assignedDepartment" = 2
    "assignedTeam" = 1
    "assignedAgent" = 16
}
New-PuTicket @splat
```

**Comment by PowershellKnut** [comment]
Vi har 12 samhandlingssoner og 59 teams fordelt under disse. Kan det være jeg burde hatt på noen flere parametere tro?

Dette er kommandoen jeg kjørte:

```powershell
$Properties = @{
    subject = "Testsak laget med API"
    description = "Testsak laget med API. Blablabla, 1234"
    assignedAgent = $(Get-PuUsers -filter 'credentials.username=="AgentEpost"').id
    user = $(Get-PuUsers -filter 'credentials.username=="BrukerEpost"').id
    assignedDepartment = 1
    assignedTeam = 16
    ticketType = 2
    priority = 3
    status = 6
    source = 2
    visibility = 0
}

New-PuTicket @Properties
```

**Comment by PowershellKnut** [comment]
> Jeg fant et lite script som du muligens kunne ha prøvd ut. Her må man endre på `Dynamic values` i param blokken til å matche deres Pureservice installasjon. Alle disse verdiene burde være mulig å finne ved å både se på eksisterende tickets, eller ved bruk av de andre funksjonene.
> 
> ```powershell
> param (
>     #Non-default values
>     [string]$Subject = "test av API æøå",
>     [string]$Description = "test123 123test! æøå",
>     [string]$AgentUsername = "AGENT_USERNAME",
>     [string]$AssignedUsername = "ENDUSER_USERNAME",
> 
>     #Dynamic values
>     [string]$PriorityName = "Normal",
>     [string]$StatusName = "Ny",
>     [string]$TeamName = "IT-servicedesk_test",
>     [string]$TicketTypeName = "Problem",
>     [string]$DepartmentName = "IT-seksjonen(test)",
>     #Depends on whether the inquiry is on chat, phone, direct, or mail
>     [string]$SourceName = "Direkte",
> 
>     #Static values
>     [string]$VisibilityName = "Visible"
> )
> 
> #Install required modules
> $RequiredModulesNameArray = @('NN.Pureservice')
> $RequiredModulesNameArray.ForEach({
>     if (Get-InstalledModule $_ -ErrorAction SilentlyContinue) {
>         Import-Module $_ -Force
>     } else {
>         Install-Module $_ -Force -Repository PSGallery
>     }
> })
> 
> $PriorityId = (Get-PuPriorities).where({$_.name -like $PriorityName})[0].id
> $SourceId = (Get-PuSources -Type "Ticket").where({$_.name -like $SourceName})[0].id
> $StatusId = (Get-PuStatuses).where({$_.name -like $StatusName})[0].id
> $TeamId = (Get-PuTeams).where({$_.name -like $TeamName})[0].id
> $AgentId = (Get-PuUsers -filter @"
> !Disabled AND (role == `"Agent`" || role == `"Administrator`") AND (credentials.username==`"$AgentUsername`")
> "@)[0].id
> $UserId = (Get-PuUsers -filter @"
> !Disabled AND (credentials.username==`"$AssignedUsername`")
> "@)[0].id
> $VisibilityId = (Get-PuVisibilityList).where({$_.Name -like $VisibilityName})[0].id
> $TicketTypeId = (Get-PuTypes -TypeCategory "Ticket").where({$_.Name -like $TicketTypeName})[0].id
> $DepartmentId = (Get-PuDepartments).where({$_.name -like $DepartmentName})[0].id
> 
> $Splat = @{
>     "subject" = $Subject
>     "description" = $Description
>     "visibility" = $VisibilityId
>     "user" = $UserId
>     "ticketType" = $TicketTypeId
>     "priority" = $PriorityId
>     "status" = $StatusId
>     "source" = $SourceId
>     "assignedDepartment" = $DepartmentId
>     "assignedTeam" = $TeamId
>     "assignedAgent" = $AgentId
> }
> New-PuTicket @splat
> ```
> 
> Det eneste som er litt dumt med dette scriptet er at det henter ut mesteparten av IDs ved hjelp av displaynames som kan endre på seg. Derfor ville jeg heller ha hentet ut alle IDene du trenger til å opprette en sak på forhånd, så lime de inn som statiske verdier i scriptet. Dette kan gjøres ved å kjøre f.eks. `Get-PuVisibilityList` for å finne visibility IDen du skal bruke.
> 
> Naturligvis vil du mest sannsynelig ikke ha alle verdier statisk, som f.eks. `subject`,`description`,`user` og `agent`, men du vil trolig kunne sette resten av verdiene til statiske IDer.
> 
> Etter verdiene er lagt inn, så vil `New-PuTicket` scriptet se noe slik ut:
> 
> ```powershell
> $Splat = @{
>     "subject" = "Tittel"
>     "description" = "Beskrivelse"
>     "visibility" = 1
>     "user" = 12
>     "ticketType" = 1
>     "priority" = 2
>     "status" = 3
>     "source" = 1
>     "assignedDepartment" = 2
>     "assignedTeam" = 1
>     "assignedAgent" = 16
> }
> New-PuTicket @splat
> ```

Takk! Jeg skal sjekke det ut.

**Comment by PowershellKnut** [comment]
Det var en feil på vår installasjon av pureservice som er fikset nå, ikke noe galt med din modul. Alt i orden, beklager bryet!

**Comment by NorskNoobing** [comment]
Supert! Tenker fortsatt at det kreves dokumentasjon av funksjonene, siden det er fullstendig manglende. Skal også få prøvd å legge inn noen eksempler på script.
